site_name: "OTEL Collector Guide"
theme:
  name: 'material'

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Troubleshooting: troubleshooting.md

# 사이트 빌드 시 글로벌 설정(예: 링크, 폰트, 검색 등)을 여기에 추가할 수 있습니다.